name: Run tests

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing node_modules
        run: npm install
      - name: Running tests
        run: npm run test